spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ingenio_db
    username: ingenio
    password: ingenio
  jpa:
    hibernate:
      hbm2ddl:
        auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER




server:
   port: 8089

security:
  jwt:
    token:
      secret-key: kh7FySn5y5Ns0Af5uh2ZowHCQsKfUT9b
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
      
UserController:
  signin: Autentica al usuario y devuelve su token JWT.
  signup: Crea un usuario y devuelve su token JWT
  delete: Elimina un usuario específico por nombre de usuario
  search: Devuelve usuario específico por nombre de usuario
  profile: Devuelve los datos del usuario actual